steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "***********************"
  
- id: 'kustomize-build'
  name: 'docker.io/lyft/kustomizer:v3.3.0'
  dir: /workspace
  args: ['kustomize', 'build', distribution, '-o', deploy/sync.yaml]

- id: 'git-push'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git remote set-url origin https://$$GITOPS_DEPLOY_GH_USERNAME:$$GITOPS_DEPLOY_GH_TOKEN@github.com/mbychkowski/gcp-config-controller-source.git

      git add -A
      git commit -m "Kustomize build config sync declarative state"
      git branch -M main
      git push -u origin main
  secretEnv: ['GITOPS_DEPLOY_GH_TOKEN', 'GITOPS_DEPLOY_GH_USERNAME']

# - id: 'Git clone deploy repo'
#   name: 'alpine/git'
#   entrypoint: 'sh'
#   dir: /workspace
#   args: 
#   - '-c'
#   - | 

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_TOKEN/versions/latest
      env: GITOPS_DEPLOY_GH_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_USERNAME/versions/latest
      env: GITOPS_DEPLOY_GH_USERNAME      
