steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace/dry-repo
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$TAG_NAME"
      echo "***********************"

      mkdir ../wet

- id: 'kustomize-build'
  name: 'gcr.io/cloud-builders/kubectl'
  dir: /workspace
  args: ['kustomize', 'distribution', '-o', 'wet/sync.yaml']
  env:
  - CLOUDSDK_COMPUTE_REGION=us-central1-c
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c
  - CLOUDSDK_CONTAINER_CLUSTER=argocd-cluster

- id: 'gcloud-source-repo'
  name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  dir: /workspace
  args: ['source', 'repos', 'clone', 'gcp-pipeline-operator-hydrated', '--project=mbychkowski-lab']

- id: 'git-push'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      cd gcp-pipeline-operator-hydrated
      
      git config --global user.email "admin@mbychkowski.altostrat.com"
      git config --global user.name "Michael Bychkowski"
      git config --global pull.rebase true
      
      git checkout main
      git pull origin main
      
      echo 'moving file to repo...'
      mv ../wet/* deploy/
      
      git add .
      git status
      git commit -m "Hydrate kubernets resources with $TAG_NAME build."
      git push origin main

# Deploy
- id: 'deploy'
  name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  dir: /workspace/dry-repo/deploy
  waitFor: ['run-buildpack']
  args: ['deploy', 'releases', 'gcp-pipeline-release-$TAG_NAME', '--project=mbychkowski-lab', '--region=us-central1', '--delivery-pipeline=my-gke-demo-app-1', '--images=my-app-image=us-central1-docker.pkg.dev/mbychkowski-lab/gcp-pipeline/echoserver:1.4']
