steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$TAG_NAME"
      echo "***********************"

      mkdir deploy

# - id: 'configure-gke'
#   name: 'gcr.io/cloud-builders/gcloud'
#   dir: /workspace
#   args: ['container', 'clusters', 'get-credentials', 'argocd-cluster', '--zone', 'us-central1-c', '--project', 'mbychkowski-lab']

- id: 'kustomize-build'
  name: 'gcr.io/cloud-builders/kubectl'
  dir: /workspace
  args: ['kustomize', 'distribution', '-o', 'deploy/sync.yaml']
  env:
  - CLOUDSDK_COMPUTE_REGION=us-central1-c
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c
  - CLOUDSDK_CONTAINER_CLUSTER=argocd-cluster

- id: 'gcloud-source-repo'
  name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  dir: /workspace
  args: ['source', 'repos', 'clone', 'gcp-pipeline-operator-hydrated', '--project=mbychkowski-lab']

- id: 'git-push'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      mv deploy/* gcp-pipeline-operator-hydrated/deploy/
      cd gcp-pipeline-operator-hydrated
      ls -la
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git pull origin main
      git add -A
      git commit -m "Hydrate kustomize files"
      git push origin main
