steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "***********************"
  
- id: 'kustomize-build'
  name: 'docker.io/lyft/kustomizer:v3.3.0'
  dir: /workspace
  args: ['kustomize', 'build', distribution, '-o', deploy/sync.yaml]

- id: 'kustomize-build'
  name: 'docker.io/lyft/kustomizer:v3.3.0'
  dir: /workspace
  args: 
  - '-c'
  - | 
      gcloud init
      gcloud source repos clone gcp-pipeline-operator-hydrated --project=mbychkowski-lab

- id: 'git-push'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      cd gcp-pipeline-operator-hydrated      
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git add -A
      git commit -m "Hydrated kustomize files"
      git branch -M main
      git push -u origin main
