steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$TAG_NAME"
      echo "***********************"
  
- id: 'kustomize-build'
  name: 'gcr.io/cloud-builders/kubectl'
  dir: /workspace
  args: ['apply', '-k' 'build', distribution, '-o', deploy/sync.yaml]

- id: 'clone-source-repo'
- name: 'gcr.io/cloud-builders/gcloud'
  dir: /workspace
  args: 
  - | 
      init && source repos clone gcp-pipeline-operator-hydrated --project=mbychkowski-lab

- id: 'git-push'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      cd gcp-pipeline-operator-hydrated      
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git add -A
      git commit -m "Hydrate kustomize files"
      git branch -M main
      git push -u origin main
