apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-gke-demo-app-1
description: "main application pipeline"
serialPipeline:
 stages:
 - targetId: cc-dev
   profiles: []
 - targetId: cc-prod
   profiles: []      
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cc-dev
description: development cluster
gke:
 cluster: projects/mbychkowski-lab/locations/us-east1/clusters/krmapihost-configcontroller
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cc-prod
description: production cluster
gke:
 cluster: projects/mbychkowski-lab/locations/us-east1/clusters/configcontroller-prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cc-canary
description:  production cluster 
gke:
  cluster: projects/mbychkowski-lab/locations/us-east1/clusters/configcontroller-prod