apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-gke-demo-app-1
description: "main application pipeline"
serialPipeline:
 stages:
 - targetId: cc-dev
   profiles: []
 - targetId: cc-prod
   profiles: []      
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cc-dev
description: "development cluster"
gke:
 cluster: projects/mbychkowski-lab/locations/us-east1/clusters/krmapihost-configcontroller
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cc-prod
description:  |
  production cluster (external, as stable as it can be).
  Used for Traffic Splitting to bedew 10% of Traffic into
  this canary (while 90% goes to canary) for some time before
  promoting all traffic to prod.
gke:
 cluster: projects/mbychkowski-lab/locations/us-east1/clusters/configcontroller-prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cc-canary
description:  |
  production cluster with canary deployment.
  Used to showcase canary deployment within a single cluster
  before promoting all traffic to newest version.
gke:
  cluster: projects/mbychkowski-lab/locations/us-east1/clusters/configcontroller-prod